apiVersion: v1
kind: Service
metadata:
  name: dev-template-ssh
  namespace: dev-template
  labels:
    app: dev-template
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
    protocol: TCP
    name: ssh
  selector:
    app: dev-template
