apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-container
  namespace: dev-environment
  labels:
    app.kubernetes.io/name: dev-container
    app.kubernetes.io/component: development
    app.kubernetes.io/part-of: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dev-container
      app.kubernetes.io/component: development
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dev-container
        app.kubernetes.io/component: development
        app.kubernetes.io/part-of: infrastructure
    spec:
      containers:
      - name: dev-container
        image: dev-container:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          name: ssh
          protocol: TCP
        env:
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-container-secrets
              key: SSH_PASSWORD
        - name: WORKSPACE_PATH
          valueFrom:
            configMapKeyRef:
              name: dev-container-config
              key: WORKSPACE_PATH
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: dev-container-config
              key: NODE_ENV
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: dev-container-config
              key: DEBUG
        # Database environment variables (from existing secrets)
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: pg-app
              key: host
              optional: true
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: pg-app
              key: port
              optional: true
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-app
              key: database
              optional: true
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-app
              key: username
              optional: true
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-app
              key: password
              optional: true
        # Redis environment variables (from existing secrets)
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-app
              key: host
              optional: true
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis-app
              key: port
              optional: true
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-app
              key: password
              optional: true
        # MinIO environment variables (from existing secrets)
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: minio-app
              key: endpoint
              optional: true
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-app
              key: access-key
              optional: true
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-app
              key: secret-key
              optional: true
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: workspace-storage
          mountPath: /workspace
        - name: ssh-keys
          mountPath: /home/developer/.ssh
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
      volumes:
      - name: workspace-storage
        persistentVolumeClaim:
          claimName: dev-container-workspace
      - name: ssh-keys
        secret:
          secretName: dev-container-ssh-keys
          defaultMode: 0600
          optional: true
      restartPolicy: Always
      securityContext:
        runAsNonRoot: false
        fsGroup: 0
