apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-container-workspace
  namespace: dev-environment
  labels:
    app.kubernetes.io/name: dev-container
    app.kubernetes.io/part-of: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
