apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-template
  namespace: dev-template
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: dev-template
        env:
        - name: NODE_ENV
          value: "production"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
