apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dev-template-production

namespace: dev-template

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

commonLabels:
  environment: production

images:
  - name: docker4zerocool/dev-template
    newTag: latest