apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-template-config
  namespace: dev-template
  labels:
    app: dev-template
data:
  NODE_ENV: "production"
  APP_NAME: "dev-template"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "info"