apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dev-template-base

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app: dev-template
  version: v1.0.0

images:
  - name: docker4zerocool/dev-template
    newTag: latest