apiVersion: v1
kind: Namespace
metadata:
  name: dev-pynode
  labels:
    name: dev-pynode
    app: dev-pynode
    managed-by: kustomize
  annotations:
    description: "Namespace for dev-pynode application"
    contact: "Bionic-AI-Solutions"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-pynode-quota
  namespace: dev-pynode
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "4"
    pods: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-pynode-limits
  namespace: dev-pynode
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      storage: "10Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim

