apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-template-pvc
  namespace: dev-template
  labels:
    app: dev-template
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
