apiVersion: v1
kind: Service
metadata:
  name: dev-template-service
  namespace: dev-template
  labels:
    app: dev-template
spec:
  type: ClusterIP
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
    name: ssh
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: frontend
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: fastapi
  selector:
    app: dev-template